services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spring_boot'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
